### ISSUE TITLE
info 

### ISSUE THREAD

**Issue by palladinoandrea** [aleixsr/HP-Pavilion-Aero-13-Hackintosh#10]
how did you make the keyboard LED work and also the brightness control

**Comment by aleixsr** [comment]
Did you tried my EFI?
I followed Noot guide, what issue are you having exactly?

**Comment by palladinoandrea** [comment]
I have a 255 g8 and I wanted to test yours to see how you did it

**Comment by aleixsr** [comment]
Check ACPI entries and also BrightnessKeys.kext

**Comment by palladinoandrea** [comment]
acpi entries are those generated via ssdtime.  Does Smclight not have to be present?

**Comment by aleixsr** [comment]
Please check my EFI, there you'll see which entries are enabled are which aren't.
