### ISSUE TITLE
Help from WIFI

### ISSUE THREAD

**Issue by Funnyland** [aleixsr/HP-Pavilion-Aero-13-Hackintosh#11]
Hello can you tell me what you did to get the WIFI to work? 

I have a Ryzen 7 5700U Mini PC so exactly something else but no matter what I try I can't get the Intel AX200 or AX210 card to work. I have tried all the instructions there are to find. I start Windows or Linux on the computer and the cards work.

The funny thing is I take the DSDT-S3 file and the SSDT-EC.aml from your EFI and put them into my EFI and my wifi works.

Do you still have the original DSTD file?

Can you please tell me how you did it so that I can use my EFI. Thanks a lot

**Comment by aleixsr** [comment]
Hello, check this guide https://chefkissinc.github.io/guide/gathering-files/acpi

Here is all I did, anyway I think this SSDTs are not related to Wi-Fi.

**Comment by Funnyland** [comment]
Hello and thank you for getting in touch.

I've long since gotten over that point.

Numerous forums have already tried to get my small computer to work with the WiFi.
Strangely enough, my WiFi only works with your SSDT-EC and DSDT-S3.aml files.

Strictly speaking, I don't have a laptop but a Ryzen 7 5700U Mini PC and that shouldn't work.

Several forum moderators have asked me to ask you if you still have the original DSDT file. ??

You can also read it here in the forum:
https://www.tonymacx86.com/threads/mini-pc-amd-ryzen-7-5700u-need-installation-help.329458/

You would help me a lot because even the moderators can't find the error.

Thank you

**Comment by aleixsr** [comment]
You're a lucky boy, because I'm currently using it and files are still there since last september that I generated it.
Here you're.
[DSDT.zip](https://github.com/aleixsr/HP-Pavilion-Aero-13-Hackintosh/files/15142471/DSDT.zip)

**Comment by Funnyland** [comment]
You are the best, I thank you with all my heart.

**Comment by Funnyland** [comment]
Unfortunately it was the same file DSDT and DSDT-S3 from your EFI are identical

**Comment by aleixsr** [comment]
I generted DSDT again, please check.
[Uploading DSDT_aml.zip…]()
