### ISSUE TITLE
Cannot set resolution to UHD (2560 x 1440)

### ISSUE THREAD

**Issue by aleixsr** [aleixsr/HP-Pavilion-Aero-13-Hackintosh#3]
No idea wha's happening...

**Comment by alarsama** [comment]
Hi! If you did want to set the resolution to 2560 x 1440, you can try BetterDisplay. I just tried it on my Aero 13 and it works... though the scaling is awful! https://github.com/waydabber/BetterDisplay

P.S. Your EFI helped get my Aero 13 up and running as well. Thank you!

**Comment by aleixsr** [comment]
Use BetterDisplay.app
