### ISSUE TITLE
How to enable 4G Decoding

### ISSUE THREAD

**Issue by aleixsr** [aleixsr/HP-Pavilion-Aero-13-Hackintosh#8]
1. Download UMAF tool
2. Reboot from pendrive, custom BIOS will appear
3. Select PCI Subsystem Settings
4. Above 4G decoding [x]
5. Re-size BAR Support [Auto]
6. Press F10 to Save Settings
7. Press 'Esc' until you get back to main menu and click on 'Continue' and 'Reboot'.

**Comment by laris** [comment]
https://github.com/DavidS95/Smokeless_UMAF

**Comment by laris** [comment]
https://github.com/aleixsr/HP-Pavilion-Aero-13-Hackintosh/issues/7
