### ISSUE TITLE
Built-in microphone visible but does not capture sound

### ISSUE THREAD

**Issue by alarsama** [aleixsr/HP-Pavilion-Aero-13-Hackintosh#9]
Hi Aleix! I am aware that compatibility between AMD hackintoshes and microphones can be iffy (both laptop mics and line-in). For this laptop, have you come upon a solution for this?

If not, while I wait for an update for AppleALC, I ended up buying these USB mini microphones on Amazon. It's a bit annoying to have hanging off the side of the laptop, but it otherwise works just fine for FaceTime! https://www.amazon.com/KISEER-Microphone-Desktop-Recording-YouTube/dp/B071WH7FC6/

**Comment by aleixsr** [comment]
Thanks, I'll check it when I'm not busy...

**Comment by aleixsr** [comment]
Confirmed issue.

**Comment by aleixsr** [comment]
Hi, solution found here: https://github.com/qhuyduong/AMDMicrophone
I'll update me EFI soon.
